# Generated by Django 3.1.7 on 2021-10-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('feedback', models.CharField(max_length=200)),
                ('month', models.IntegerField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
