# Generated by Django 3.1.7 on 2021-10-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expensesdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesdetails',
            name='feedback',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
